### ISSUE TITLE
Unable to guess `text/turtle` type

### ISSUE THREAD

**Issue by timothee-haudebourg** [ebassi/xdg-mime-rs#19]
Hi,

Here's the simple code I use to read a [Turtle](https://en.wikipedia.org/wiki/Turtle_(syntax)) file:
```rust
let filename = path.file_name().unwrap().to_str().unwrap();
let meta = std::fs::metadata(path)?;
let mut file = File::open(path)?;
let mut buffer = [0; 512];
file.read(&mut buffer)?;

let guess = mime_db.guess_mime_type().file_name(filename).metadata(meta).data(&buffer[0..len]).guess();
```
It is unable to guess the correct `text/turtle` type for the following file:
```turtle
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix ex: <http://example.org/stuff/1.0/> .

<http://www.w3.org/TR/rdf-syntax-grammar>
  dc:title "RDF/XML Syntax Specification (Revised)" ;
  ex:editor [
    ex:fullname "Dave Beckett";
    ex:homePage <http://purl.org/net/dajobe/>
  ] .
```
and instead guesses `text/plain`. It sometimes succeeds on some other Turtle files. Note that the following command successfully find the correct media type:
```
$ xdg-mime query filetype example.ttl
text/turtle
```

Also note that on `example.ttl`, `get_mime_types_from_file_name` returns a `Vec` of size 2 with the duplicate entry `text/turtle`.

**Comment by ebassi** [comment]
Thanks for your patience.

Looking into the shared-mime-info database it seems that Turtle files are only matched through their glob pattern, not their data.

This sample test code works with xdg-mime-rs 0.3:

```rust
let ttl_data = include_bytes!("example.ttl"); // the example file you included
let mime_db = SharedMimeInfo::new();
let mut gb = mime_db.guess_mime_type();
let guess = gb.file_name("example.ttl").data(ttl_data).guess();
assert_eq!(
    guess.mime_type(),
    &Mime::from_str("text/turtle").unwrap()
);
```

If I add a `metadata()` invocation:

```rust
let cwd = env::current_dir().unwrap().to_string_lossy().into_owned();
let ttl_file = PathBuf::from("example.ttl");
let ttl_data = include_bytes!("example.ttl");
let ttl_meta = std::fs::metadata(ttl_file).unwrap();
let mime_db = SharedMimeInfo::new();
let mut gb = mime_db.guess_mime_type();
let guess = gb
    .file_name("example.ttl")
    .metadata(ttl_meta)
    .data(ttl_data)
    .guess();
assert_eq!(
    guess.mime_type(),
    &Mime::from_str("text/turtle").unwrap()
);
```
the assertion is still not triggered.

Which version of xdg-mime-rs are you using?

**Comment by ebassi** [comment]
For reference, I've added the example file to the test suite, and it seems to pass.

**Comment by timothee-haudebourg** [comment]
Using your code I get the same error
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"text/plain"`,
 right: `"text/turtle"`', bin/main.rs:12:
```

I'm starting to think the problem comes from the mime infos stored on my computer... But if that's the case, why `xdg-mime query` command is able to find the correct type? Could it be possible that the crate is not loading all the available data using `SharedMimeInfo::new()`?

**Comment by ebassi** [comment]
> I'm starting to think the problem comes from the mime infos stored on my computer...

I find it unlikely, but it should be easy to check: in the `/usr/share/mime/globs2` file you should find a line like this one:

```
50:text/turtle:*.ttl
```

Additionally, the `magic` file at the same location should not have any magic definition for the `text/turle` MIME type.

> But if that's the case, why xdg-mime query command is able to find the correct type?

[`xdg-mime`](https://gitlab.freedesktop.org/xdg/xdg-utils/-/blob/master/scripts/xdg-mime.in) is just a shell script that calls other commands depending on the environment. For instance, under GNOME, using `xdg-mime query filetype example.ttl` it will call:

 ```
gio info example.ttl | grep standard::content-type | cut -f 4 -d' '
```

Under other environments it might call something completely different, which may or may not include the shared-mime-info database. For instance, if no known environment was found, it will call the `file` command, which uses its own magic definitions.

> Could it be possible that the crate is not loading all the available data using `SharedMimeInfo::new()`?

Not really, no. The only thing that the crate isn't loading, at the moment, is the mmap'able binary cache, but both the various files and the cache are generated from the same data.

**Comment by timothee-haudebourg** [comment]
I found the `50:text/turtle:*.ttl` line. What's weird is that `get_mime_types_from_file_name` is able to find `text/turtle`, and only that.

I don't understand why `get_mime_types_from_file_name` can find the correct type but `guess_mime_type` won't.

**Comment by ebassi** [comment]
Neither do I:

 - `guess_mime_type()` calls `get_mime_types_from_file_name()`
 - the data is discarded if there are no matches when sniffing the file contents

**Comment by timothee-haudebourg** [comment]
I've cloned the repo and been able to reproduce the problem with the sources. I'll try to debug this more precisely tomorrow.

**Comment by timothee-haudebourg** [comment]
line 348 of `lib.rs` the call `self.db.get_mime_types_from_file_name(&file_name)` returns `["text/turtle", "text/turtle"]` as observed before. I think having a duplicate entry might be the source of the problem here.

Line 353 you check the presence of conflicts by checking the length of the returned vec, `name_mime_types.len() == 1`. It will fail in this case, even is there are no real conflicts.

Maybe you should use `HashSet` instead of `Vec` to avoid this to happen?

**Comment by ebassi** [comment]
> I think having a duplicate entry might be the source of the problem here.

Oh, this is interesting. Do you have a copy of the shared-mime database in two places, like /usr/share and /usr/local/share?

> Maybe you should use `HashSet` instead of `Vec` to avoid this to happen?

Yes, that'd be a solution; though it needs to check if both the glob and the MIME type are identical, otherwise it would prevent having overrides.

**Comment by timothee-haudebourg** [comment]
> Do you have a copy of the shared-mime database in two places

That's might be possible. I run on NixOS, which is weird enough I can imagine many ways this can happen.
