### ISSUE TITLE
Warning about `dirs` crate being unmaintained

### ISSUE THREAD

**Issue by hunger** [ebassi/xdg-mime-rs#25]
Github is sending security warnings about my project since it started to depend on xdg-mime.

Accoring to the advisory (link beliw) the `dirs` crate is unmaintained and the `dirs-next` shoumd be used instead. Both crates seem to have identical APIs.

https://github.com/RustSec/advisory-db/blob/main/crates/dirs/RUSTSEC-2020-0053.md

**Comment by ebassi** [comment]
This was fixed in #24.

**Comment by hunger** [comment]
Thank you!
