### ISSUE TITLE
`SharedMimeInfo::get_mime_types_from_file_name()` returns guesses in a wrong order

### ISSUE THREAD

**Issue by albel727** [ebassi/xdg-mime-rs#27]
`SharedMimeInfo::get_mime_types_from_file_name()` and respectively `GlobMap::lookup_mime_type_for_file_name()` return mime guesses in a wrong/unintuitive order, with the less likely mime-types before the more likely ones.

The offending line is https://github.com/ebassi/xdg-mime-rs/blob/23204a3e112447e5d8fdf7b2301f5e9d6f29fe13/src/glob.rs#L285 which sorts the matching globs in the ascending weight order, instead of the descending one.

This affects `GuessBuilder::guess()` too, as it assumes in general that `get_mime_types_from_file_name()` returns the more likely mimes first, e.g:
https://github.com/ebassi/xdg-mime-rs/blob/23204a3e112447e5d8fdf7b2301f5e9d6f29fe13/src/lib.rs#L430-L432

## Reproduction
Given `globs2` with
```
50:audio/x-mod:*.mod
40:application/x-object:*.mod
```

`get_mime_types_from_file_name(".mod")` returns `["application/x-object", "audio/x-mod"]`

## Expected result

It should return `["audio/x-mod", "application/x-object"]`

**Comment by ebassi** [comment]
Fixed in 0.4.0.
